import { useState } from 'react';
import OrderNotes from './OrderNotes';
import { createAdminCheckoutSession, updateOrderAmount } from '../../services/api';

export const STATUS_LABELS={REQUESTED:'Solicitud nueva',UNDER_REVIEW:'En revisión',QUOTED:'Cotizado',AWAITING_PAYMENT:'Pendiente de pago',PAID:'Pagado',SCHEDULED:'Programado',UNIT_ASSIGNED:'Unidad asignada',READY_TO_DEPART:'Listo para salir',IN_TRANSIT:'En ruta',AT_CUSTOMS:'En aduana',DELIVERED:'Entregado',CANCELLED:'Cancelado'};
const PAYMENT_LABELS={PENDING:'Pendiente',PARTIALLY_PAID:'Pago parcial',PAID:'Pagado',FAILED:'Fallido',REFUNDED:'Reembolsado',CANCELLED:'Cancelado'};
const money=(cents)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format((cents||0)/100);

export default function OrderCard({ order, updating, onStatus, onEdit, onReload }) {
  const [copied,setCopied]=useState(false),[amount,setAmount]=useState(order.totalAmountCents?String(order.totalAmountCents/100):''),[paymentBusy,setPaymentBusy]=useState(false),[paymentError,setPaymentError]=useState('');
  const trackingNumber=order.trackingNumber||order.trackingCode;
  const privateLink=order.trackingToken?`${window.location.origin}/rastreo?token=${order.trackingToken}`:'';
  function status(event){const value=event.target.value;if(['DELIVERED','CANCELLED'].includes(value)&&!window.confirm(`¿Confirmas cambiar el pedido a ${STATUS_LABELS[value]}?`))return;onStatus(order.id,value)}
  async function copyPrivateLink(){if(!privateLink)return;await navigator.clipboard.writeText(privateLink);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}
  async function saveAmount(event){event.preventDefault();const cents=Math.round(Number(amount)*100);if(!Number.isSafeInteger(cents)||cents<=0){setPaymentError('Ingresa un monto válido mayor a cero.');return}let confirmed=false;if(order.paymentStatus==='PAID'){confirmed=window.confirm('Este pedido ya está pagado. Cambiar el monto no modifica ni revierte el pago recibido. ¿Deseas continuar?');if(!confirmed)return}try{setPaymentBusy(true);setPaymentError('');await updateOrderAmount(order.id,cents,confirmed);await onReload?.()}catch(error){setPaymentError(error.message)}finally{setPaymentBusy(false)}}
  async function generatePayment(){try{setPaymentBusy(true);setPaymentError('');const response=await createAdminCheckoutSession(order.id);window.location.assign(response.url)}catch(error){setPaymentError(error.message);setPaymentBusy(false)}}
  return <article className="admin-order-card"><header><div><span className="admin-tracking-code">{trackingNumber}</span><div className="admin-tracking-actions"><button type="button" onClick={copyPrivateLink} disabled={!privateLink}>{copied?'Enlace copiado':'Copiar enlace privado'}</button>{privateLink?<a href={privateLink} target="_blank" rel="noreferrer">Abrir seguimiento</a>:<span>Token pendiente</span>}</div><h2>{order.client?.companyName||order.client?.contactName}</h2></div><span className={`admin-status admin-status-${order.status.toLowerCase()}`}>{STATUS_LABELS[order.status]||order.status}</span></header><section className="admin-payment"><div><span>Monto total</span><strong>{order.totalAmountCents?money(order.totalAmountCents):'Sin asignar'}</strong><small>{PAYMENT_LABELS[order.paymentStatus]||order.paymentStatus}</small></div><form onSubmit={saveAmount}><label>Monto en MXN<input type="number" min="0.01" step="0.01" value={amount} onChange={(event)=>setAmount(event.target.value)} disabled={paymentBusy}/></label><button disabled={paymentBusy}>{paymentBusy?'Guardando…':'Guardar monto'}</button></form>{order.totalAmountCents>0&&order.paymentStatus!=='PAID'&&order.trackingToken&&<button type="button" onClick={generatePayment} disabled={paymentBusy}>Generar pago de prueba</button>}{paymentError&&<p className="admin-form-error">{paymentError}</p>}</section><div className="admin-order-grid"><div><span>Contacto</span><strong>{order.client?.contactName}</strong><small>{order.client?.phone||'Sin teléfono'}</small></div><div><span>Origen</span><strong>{order.originAddress}</strong></div><div><span>Destino</span><strong>{order.destinationAddress}</strong></div><div><span>Unidad</span><strong>{order.vehicle?.internalCode||'Sin asignar'}</strong><small>{order.vehicle?.plateNumber}</small></div><div><span>Operador</span><strong>{order.driver?.fullName||'Sin asignar'}</strong><small>{order.driver?.phone}</small></div></div><div className="admin-status-control"><label>Cambiar estado</label><select value={order.status} disabled={updating} onChange={status}>{Object.entries(STATUS_LABELS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><button type="button" onClick={()=>onEdit(order)}>Editar pedido</button>{updating&&<span>Guardando...</span>}</div><OrderNotes order={order} onAdded={onReload}/><details className="admin-history"><summary>Ver historial ({order.statusHistory?.length||0})</summary><ol>{(order.statusHistory||[]).map(event=><li key={event.id}><strong>{STATUS_LABELS[event.newStatus]}</strong><span>{new Date(event.createdAt).toLocaleString('es-MX')}</span>{event.notes&&<p>{event.notes}</p>}</li>)}</ol></details></article>;
}
