import { useCallback, useEffect, useState } from 'react';
import { convertServiceRequest, getServiceRequests, updateServiceRequestStatus } from '../../services/api';

const labels = { PENDING: 'Pendiente', UNDER_REVIEW: 'En revisión', CONTACTED: 'Contactado', REJECTED: 'Rechazado', CONVERTED: 'Convertido' };
export default function ServiceRequestsPanel({ onOrderCreated }) {
  const [requests, setRequests] = useState([]); const [filters, setFilters] = useState({ search: '', status: '', date: '', serviceType: '' }); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); const data = await getServiceRequests(filters); setRequests(data.requests || []); } catch (e) { setError(e.message); } }, [filters]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  async function status(id, value) { let reason = ''; if (value === 'REJECTED') { reason = window.prompt('Motivo del rechazo (obligatorio):')?.trim() || ''; if (!reason) return; } try { setBusy(id); setError(''); await updateServiceRequestStatus(id, value, reason); setMessage('Solicitud actualizada.'); await load(); } catch (e) { setError(e.message); } finally { setBusy(''); } }
  async function convert(item) { if (!window.confirm(`¿Aprobar y convertir ${item.requestNumber} en cliente y pedido?`)) return; try { setBusy(item.id); setError(''); const data = await convertServiceRequest(item.id); setMessage(`${data.alreadyConverted ? 'El pedido ya existía' : 'Pedido creado'}: ${data.trackingNumber}. Enlace privado: ${data.privateUrl}`); await load(); await onOrderCreated?.(data.order?.id); } catch (e) { setError(e.message); } finally { setBusy(''); } }
  return <section className="service-requests-admin"><header><div><p className="admin-eyebrow">Entrada pública</p><h2>Solicitudes de servicio</h2></div><button type="button" onClick={load}>Actualizar</button></header>
    <div className="request-admin-filters"><input aria-label="Buscar solicitudes" placeholder="Buscar folio, nombre, correo o teléfono" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select aria-label="Estado" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Todos los estados</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><input aria-label="Fecha de envío" type="date" value={filters.date} onChange={(e) => setFilters({ ...filters, date: e.target.value })} /><input aria-label="Tipo de servicio" placeholder="Tipo de servicio" value={filters.serviceType} onChange={(e) => setFilters({ ...filters, serviceType: e.target.value })} /></div>
    {error && <p className="admin-error" role="alert">{error}</p>}{message && <p className="admin-success" role="status">{message}</p>}
    <div className="request-admin-list">{requests.length ? requests.map((item) => <details className="request-admin-card" key={item.id}><summary><span><strong>{item.requestNumber}</strong>{item.fullName} · {item.serviceType}</span><b>{labels[item.status] || item.status}</b></summary><div className="request-admin-detail"><dl><div><dt>Contacto</dt><dd>{item.phone}<br />{item.email}{item.companyName ? <><br />{item.companyName}</> : null}</dd></div><div><dt>Ruta</dt><dd>{item.originAddress}<br />→ {item.destinationAddress}</dd></div><div><dt>Descripción</dt><dd>{item.cargoDescription}</dd></div><div><dt>Fechas</dt><dd>Deseada: {item.requestedDate ? new Date(item.requestedDate).toLocaleDateString('es-MX') : 'Sin definir'}<br />Envío: {new Date(item.createdAt).toLocaleString('es-MX')}</dd></div></dl>{(item.vehicleMake || item.vehicleModel || item.vehicleYear || item.vehicleVin) && <p><strong>Vehículo:</strong> {[item.vehicleMake, item.vehicleModel, item.vehicleYear, item.vehicleVin].filter(Boolean).join(' · ')}</p>}{item.comments && <p><strong>Comentarios:</strong> {item.comments}</p>}{item.rejectionReason && <p><strong>Motivo de rechazo:</strong> {item.rejectionReason}</p>}<div className="request-admin-actions">{item.status === 'PENDING' && <button disabled={busy === item.id} onClick={() => status(item.id, 'UNDER_REVIEW')}>Marcar en revisión</button>}{!['REJECTED', 'CONVERTED'].includes(item.status) && <button disabled={busy === item.id} onClick={() => status(item.id, 'CONTACTED')}>Marcar contactado</button>}{!['REJECTED', 'CONVERTED'].includes(item.status) && <button disabled={busy === item.id} onClick={() => convert(item)}>Aprobar y convertir</button>}{!['REJECTED', 'CONVERTED'].includes(item.status) && <button className="danger" disabled={busy === item.id} onClick={() => status(item.id, 'REJECTED')}>Rechazar</button>}{item.order && <span>Pedido {item.order.trackingNumber}</span>}</div></div></details>) : <p className="admin-empty">No hay solicitudes que coincidan con los filtros.</p>}</div>
  </section>;
}
