export const units = [
  {
    id: 'MOR-401',
    company: 'Morenas',
    unitLabel: 'Tractocamión 401',
    route: 'Monterrey → Laredo',
    status: 'En ruta',
    speedKmh: 67,
    ignition: true,
    driver: 'Operador asignado',
    lastUpdate: 'Hoy · 10:42 a.m.',
    position: { lat: 25.6866, lng: -100.3161 },
    events: [
      { time: '08:15', title: 'Salida registrada', detail: 'La unidad salió del punto de origen.' },
      { time: '09:40', title: 'Avance de ruta', detail: 'La unidad reportó tránsito en el tramo principal.' },
      { time: '10:42', title: 'Actualización GPS', detail: 'La unidad continúa en ruta con señal activa.' },
    ],
  },
  {
    id: 'MOR-722',
    company: 'Morenas',
    unitLabel: 'Camión 722',
    route: 'Saltillo → Monterrey',
    status: 'Programado',
    speedKmh: 39,
    ignition: true,
    driver: 'Operador en tránsito',
    lastUpdate: 'Hoy · 11:08 a.m.',
    position: { lat: 25.4267, lng: -100.9959 },
    events: [
      { time: '07:55', title: 'Unidad asignada', detail: 'La unidad fue asignada al servicio registrado.' },
      { time: '09:12', title: 'Servicio programado', detail: 'La ruta quedó confirmada para seguimiento operativo.' },
      { time: '11:08', title: 'Monitoreo activo', detail: 'El servicio cuenta con seguimiento disponible para el cliente.' },
    ],
  },
  {
    id: 'MOR-318',
    company: 'Morenas',
    unitLabel: 'Unidad 318',
    route: 'Nuevo Laredo → Apodaca',
    status: 'En revisión',
    speedKmh: 0,
    ignition: false,
    driver: 'Operador en espera',
    lastUpdate: 'Hoy · 09:54 a.m.',
    position: { lat: 27.4763, lng: -99.5164 },
    events: [
      { time: '06:48', title: 'Servicio registrado', detail: 'La solicitud fue recibida para coordinación.' },
      { time: '08:23', title: 'Revisión operativa', detail: 'Se verifican datos de unidad y ruta antes de salida.' },
      { time: '09:54', title: 'Último estatus', detail: 'Unidad en espera con seguimiento activo.' },
    ],
  },
];
